// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package api

// Error defines model for Error.
type Error struct {
	// Code 错误码
	Code int32 `json:"code"`

	// Message 错误信息
	Message string `json:"message"`
}

// NewPet defines model for NewPet.
type NewPet struct {
	// Name pet 的名字
	Name string `json:"name"`

	// Tag pet 的标签
	Tag *string `json:"tag,omitempty"`
}

// Pet defines model for Pet.
type Pet struct {
	// Id pet 的唯一 ID
	Id int64 `json:"id"`

	// Name pet 的名字
	Name string `json:"name"`

	// Tag pet 的标签
	Tag *string `json:"tag,omitempty"`
}

// FindPetsParams defines parameters for FindPets.
type FindPetsParams struct {
	// Tags 用来过滤 pet 的标签
	Tags *[]string `form:"tags,omitempty" json:"tags,omitempty"`

	// Limit 返回的最大 pet 数量
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// AddPetJSONRequestBody defines body for AddPet for application/json ContentType.
type AddPetJSONRequestBody = NewPet
